version: 0.0
os: linux
files:
  - source: boot2-sample-0.0.1-SNAPSHOT.jar
    destination: /opt/apl
hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root