version: 0.2
 
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/boot2-sample-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/start.sh
    - scripts/stop.sh
    - scripts/beforeinstall.sh

  discard-paths: yes